name = "Perf Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2691d9909e181dac0b51eacba6bc8e779284f8571940a6d4bfa2b7f9c0927c6d"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
