name = "Perf Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a13b47e140a3166ce9cac5ea38137534510eb94155f7ffc9f2aaff36237cbd75"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
