name = "Perf Pack"
author = "Shadowevil015"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ea73a2dea5581a67640437a650b0f9409817cb88cc019b3d857457fb34e0d00"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
