name = "Perf Pack"
author = "Shadowevil015"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b8f95f4f57b1fcf57a3a940221cb9d86f69264767d9c367a722aa84291c00ac"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
