name = "Perf Pack"
author = "Shadowevil015"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c922c8f15108b01353ebe2859655f385f60a5ea0eb63302bfcb33e93b0362e69"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
