name = "Perf Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1ba165252d4e9c1340acab10f688940ae87534704f0983529a15e9ec689a338"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
