name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5faa54507ced75df5f165417c1c2cb68a15a5d62d798c3340c62286278e77f1"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
