name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c345b5a3d0cf040c3ee76b5a7d902ee125223dcc863a0b602e97e67e004e29f"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
