name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd46672b423145208971925efeec7519bd254d9afafc8a2d2d668bd45bd80d9a"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
