name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da5cb71191b0cc3ae9cc477ada486d7e2bba4042b07f35ff6fd44a9526a662c9"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
