name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df3bc37ee9ad30d476b78b1cc2b9e9bfb9c7104a4c4da688f38835a8d5923414"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
