name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e42b51e42c4291a4635429a3f08121eb9ab20634fdcc4bab8eeea3980af769d"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
