name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94d33b8eeb51384ce9f3b69bcfd7eb478636617a18c2d0d5e727fafe5fa9baad"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
