name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42dd500cc69e3e4f02196529f33cb6c37459cfde7b8fe70b98f4f73e896d11aa"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
