name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48aeef1a31b67269585694ece29b3c8825a22dc6e84dc2c81c540313f57d220d"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
