name = "PP Pack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e0a9d1dbdf0d05f9f76b43f8d3d1a58de411b03f8a51b9fc4a04cb25399945a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
